print("")
print("Hello World!\n")
print("My Journal 1.0\n")
print("Commands:\n")
print("help- Display help for the program commands")
print("new - Create a new journal entry")
print("list- List the journal entries")
print("view <date> - View a single journal entry")
print("edit <date> - Edit an existing journal entry")
print("delete <date> - Delete a existing journal entry")
print("")
